#!/bin/sh -e
# Usage:
#        [remote=] [branch=] template-local add [args]
#        [remote=] [branch=] template-local pull [args]
#
# To debug, set shell_cmd=echo to print the resulting command:
#
#        shell_cmd=echo template-local <command> <args>
#

default_remote="url_remote_repository"

# the <name> is used to identify the subtree branch and the commit among subtrees from the same repository
# it must be identical to the name used at remote
subtree_name='<name>'
subtree_prefix="path/to/subtree/at/local"
# remote repository for the subtree
subtree_remote=${remote:-"$default_remote"}
# remote branch for the subtree
subtree_branch=${branch:-"subtree-$subtree_name"}
# commit message prefix for split, means for template-remote only
subtree_annotate=${annotate:-"$subtree_name: "}

. $(dirname $0)/git-subtree $@
