#!/bin/sh -e
# Usage:
#        [branch=] [annotate=] template-remote split [args]
#
# To debug, set shell_cmd=echo to print the resulting command
#
#        shell_cmd=echo template-remote <command> <args>
#

# the <name> is used to identify the subtree branch
subtree_name='<name>'
subtree_prefix="path/to/subtree/at/remote"
# subtree_remote means for template-local only, blank by default at remote
subtree_remote=${remote:-}
# the default branch name is prefixed with 'subtree-'
subtree_branch=${branch:-"subtree-$subtree_name"}
# commit message prefix for split, make it identical for each split
subtree_annotate=${annotate:-"$subtree_name: "}

. $(dirname $0)/git-subtree $@
